CC = gcc

CFLAGS = -I./inc -I./file_handling/inc

SOURCES = main.c ./src/*.c ./file_handling/src/.*c

TARGET = run



$(TARGET): $(SOURCES)

	$(CC) -o $(TARGET) $(SOURCES) $(CFLAGS)



clean:

	rm -rf $(TARGET)